'use strict';

/**
 * usageDimensions.js — Nuvra Phase 7
 *
 * Canonical usage dimension definitions. Every billable event in the system
 * maps to exactly one dimension. Dimensions are the atomic units of the
 * Usage Ledger.
 *
 * Design principles:
 *  - Deterministic: the same action always produces the same dimension entry.
 *  - Inspectable: every dimension has a human-readable label and description.
 *  - Predictable: units are explicit and never ambiguous.
 */

// ─── Dimension IDs ────────────────────────────────────────────────────────────

const Dimension = Object.freeze({
  // AI
  AI_TOKENS_INPUT:      'ai.tokens.input',
  AI_TOKENS_OUTPUT:     'ai.tokens.output',
  AI_PLANS_EXECUTED:    'ai.plans.executed',
  AI_COST_USD:          'ai.cost.usd',

  // Generation
  PAGES_GENERATED:      'gen.pages',
  APPS_GENERATED:       'gen.apps',
  COMPONENTS_GENERATED: 'gen.components',

  // Build & Publish
  PREVIEW_MINUTES:      'build.preview.minutes',
  PUBLISH_BUILDS:       'build.publish',
  MOBILE_BUILDS:        'build.mobile',

  // Storage & Network
  STORAGE_BYTES:        'infra.storage.bytes',
  BANDWIDTH_BYTES:      'infra.bandwidth.bytes',

  // Collaboration
  COLLAB_SEATS:         'collab.seats',
});

// ─── Dimension Metadata ───────────────────────────────────────────────────────

const DIMENSION_META = Object.freeze({
  [Dimension.AI_TOKENS_INPUT]: {
    id:          Dimension.AI_TOKENS_INPUT,
    label:       'AI Input Tokens',
    description: 'Tokens sent to the AI provider in prompts.',
    unit:        'tokens',
    billable:    true,
    aggregation: 'sum',
  },
  [Dimension.AI_TOKENS_OUTPUT]: {
    id:          Dimension.AI_TOKENS_OUTPUT,
    label:       'AI Output Tokens',
    description: 'Tokens received from the AI provider in responses.',
    unit:        'tokens',
    billable:    true,
    aggregation: 'sum',
  },
  [Dimension.AI_PLANS_EXECUTED]: {
    id:          Dimension.AI_PLANS_EXECUTED,
    label:       'AI Plans Executed',
    description: 'Number of complete AI planning pipeline runs.',
    unit:        'plans',
    billable:    true,
    aggregation: 'count',
  },
  [Dimension.AI_COST_USD]: {
    id:          Dimension.AI_COST_USD,
    label:       'AI Cost',
    description: 'Estimated USD cost of AI provider calls.',
    unit:        'USD',
    billable:    true,
    aggregation: 'sum',
  },
  [Dimension.PAGES_GENERATED]: {
    id:          Dimension.PAGES_GENERATED,
    label:       'Pages Generated',
    description: 'Number of pages generated by the AI planning engine.',
    unit:        'pages',
    billable:    true,
    aggregation: 'count',
  },
  [Dimension.APPS_GENERATED]: {
    id:          Dimension.APPS_GENERATED,
    label:       'Apps Generated',
    description: 'Number of complete app schemas generated.',
    unit:        'apps',
    billable:    true,
    aggregation: 'count',
  },
  [Dimension.COMPONENTS_GENERATED]: {
    id:          Dimension.COMPONENTS_GENERATED,
    label:       'Components Generated',
    description: 'Number of components generated by the AI engine.',
    unit:        'components',
    billable:    true,
    aggregation: 'count',
  },
  [Dimension.PREVIEW_MINUTES]: {
    id:          Dimension.PREVIEW_MINUTES,
    label:       'Preview Runtime Minutes',
    description: 'Minutes of active preview runtime.',
    unit:        'minutes',
    billable:    false, // Tracked but not billed in current plans
    aggregation: 'sum',
  },
  [Dimension.PUBLISH_BUILDS]: {
    id:          Dimension.PUBLISH_BUILDS,
    label:       'Publish Builds',
    description: 'Number of publish pipeline executions.',
    unit:        'builds',
    billable:    true,
    aggregation: 'count',
  },
  [Dimension.MOBILE_BUILDS]: {
    id:          Dimension.MOBILE_BUILDS,
    label:       'Mobile Builds',
    description: 'Number of TWA/Capacitor mobile build executions.',
    unit:        'builds',
    billable:    true,
    aggregation: 'count',
  },
  [Dimension.STORAGE_BYTES]: {
    id:          Dimension.STORAGE_BYTES,
    label:       'Storage Used',
    description: 'Total bytes of project data stored in the cloud.',
    unit:        'bytes',
    billable:    false,
    aggregation: 'max', // High-water mark, not sum
  },
  [Dimension.BANDWIDTH_BYTES]: {
    id:          Dimension.BANDWIDTH_BYTES,
    label:       'Bandwidth Used',
    description: 'Total bytes transferred for published sites.',
    unit:        'bytes',
    billable:    false, // Future billing
    aggregation: 'sum',
  },
  [Dimension.COLLAB_SEATS]: {
    id:          Dimension.COLLAB_SEATS,
    label:       'Collaboration Seats',
    description: 'Number of active collaborators on projects.',
    unit:        'seats',
    billable:    true,
    aggregation: 'max',
  },
});

// ─── Entry Factory ────────────────────────────────────────────────────────────

/**
 * Creates a validated usage ledger entry.
 *
 * @param {object} params
 * @param {string} params.dimension   - One of the Dimension constants
 * @param {number} params.quantity    - The measured quantity (must be >= 0)
 * @param {string} params.userId      - The user who incurred the usage
 * @param {string} [params.projectId] - The project the usage belongs to (if applicable)
 * @param {string} [params.provider]  - The AI/cloud provider (if applicable)
 * @param {object} [params.meta]      - Additional structured metadata
 * @returns {object} A validated, immutable ledger entry
 */
function createEntry({ dimension, quantity, userId, projectId = null, provider = null, meta = {} }) {
  if (!dimension || !DIMENSION_META[dimension]) {
    throw new Error(`[UsageDimensions] Unknown dimension: "${dimension}"`);
  }
  if (typeof quantity !== 'number' || quantity < 0 || !isFinite(quantity)) {
    throw new Error(`[UsageDimensions] quantity must be a non-negative finite number, got: ${quantity}`);
  }
  if (!userId) {
    throw new Error('[UsageDimensions] userId is required');
  }

  return Object.freeze({
    id:         `ule_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`,
    dimension,
    quantity,
    userId,
    projectId,
    provider,
    meta:       Object.freeze({ ...meta }),
    recordedAt: new Date().toISOString(),
  });
}

/**
 * Returns the metadata for a given dimension.
 * @param {string} dimension
 * @returns {object}
 */
function getDimensionMeta(dimension) {
  return DIMENSION_META[dimension] || null;
}

/**
 * Returns all dimension metadata as an array.
 * @returns {object[]}
 */
function getAllDimensions() {
  return Object.values(DIMENSION_META);
}

export { Dimension, DIMENSION_META, createEntry, getDimensionMeta, getAllDimensions };